name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install toolchain
      run: bash scripts/install-toolchain.sh
      
    - name: Build firmware
      run: make firmware

